---
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: ibft
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    nonce: '0x0'
    gasLimit: '0x47b760'
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
  blockchain:
    nodes:      # refers to validators/signers
      generate: true
      count: 4
    accountPassword: 'password'

image:
  repository: consensys/quorum-k8s-hooks
  tag: qgt-0.1.7
  pullPolicy: IfNotPresent
